### ISSUE TITLE
сопоставления полей Amo CRM и JoomShopping

### ISSUE THREAD

**Issue by driverXP** [sergeytolkachyov/WT-Amo-CRM-library-for-Joomla-4#4]
Здравствуйте,

Создал в Amocrm текстовые поля: Статус заказа, Способ оплаты, Способ доставки.
Сопоставил эти поля с Joomshoping. Основные данные о заказе приходят корректно, а из сопоставленных полей вместо текстовой информации приходят цифровые значения.

Joomla 4.3.4, JoomShopping 5.2.0

**Comment by sergeytolkachyov** [comment]
@driverXP это не в этом репозитории. Сюда перенесу https://github.com/sergeytolkachyov/WT-AmoCRM---JoomShopping-Joomla-plugin
